spring.application.name=anonymousplatform
spring.datasource.url=jdbc:mysql://localhost:3306/pdl_project
spring.datasource.username=root
spring.datasource.password=sohamsql32025

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect